#!/bin/sh

emit_release () {
    project=$1
    date=$2
    prefix="${project}-${date}-git"
    url="$project/$date/${prefix}.tgz"
    archive="monkeylib/archives/$url"
    asds=`tar tzf $archive | perl -ne '/$prefix\/(.*\.asd)/ and print " $1";'`
    size=`wc -c $archive | perl -ne '/^\s+(\d+).*/ and print $1, $/;'`
    md5=`md5 $archive | perl -ne '/= (.*)/ and print $1, $/;'`
    sha1=`shasum $archive  | cut -c1-40`
    
    echo "$project $url $size $md5 $sha1 $prefix$asds"
}


for project in `ls monkeylib/archives/`; do
    for date in `ls monkeylib/archives/$project/`; do
        emit_release $project $date
    done
done

