#!/bin/bash

# Build releases.txt

project=$1
date=`date +'%Y-%m-%d'`

here=`pwd`
monkeylib_root=~/lisp/monkeylib
archive_root="$here/monkeylib/archives"
prefix="${project}-${date}-git"
archive_file="${prefix}.tgz"
archive_dir="$project/$date"
url="$archive_dir/$archive_file"
archive="$archive_root/$url"

mkdir -p $archive_root/$archive_dir

cd $monkeylib_root/$project
git archive --format=tar --prefix=${prefix}/ HEAD | gzip > $archive
